### ISSUE TITLE
v0.0.3 roadmap

### ISSUE THREAD

**Issue by tzhangchi** [aregrid/aregridjs#2]
- [x] support local-first db, 
- [x] support workspace，messages storage  #4 
- [x] support basic mobile view
- [x] install a icons solution
- [x] support export/import whole app data
