### ISSUE TITLE
v0.0.4 roadmap

### ISSUE THREAD

**Issue by tzhangchi** [aregrid/aregridjs#3]
- [ ] support docker
- [ ] snapshot affine message , Storage it as a json to chat message
- [ ] support local db sync to server db
- [ ] support share all app
