### ISSUE TITLE
v0.0.6 Roadmap

### ISSUE THREAD

**Issue by tzhangchi** [aregrid/aregridjs#5]
- [ ] Bump the BlockSuite Version
- [ ] Reference Octobase Nodejs server Architecture, such as GraphQL, Prisma,Nestjs, Postgries
- [ ] Add Account System
- [ ] Support MultiPlayer
- [ ] Support AFFiNE File Independent Storage, as blob
