### ISSUE TITLE
v0.0.5 Roadmap

### ISSUE THREAD

**Issue by tzhangchi** [aregrid/aregridjs#6]
- [ ] Support indexdb search
- [ ] Support ChatMessage As a Gallery View
- [ ] Support Workspace Setting
